language: node_js
node_js:
    - "4.2"
before_install:
    - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
    - npm install -g grunt-cli
    - npm install -g bower
    - bower install
    - npm update
    - bower update
notifications:
    email:
        on_success: change
        on_failure: change
sudo: false
